global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: backend
    static_configs:
      - targets: ["backend:8000"]
    metrics_path: /metrics

  - job_name: celery
    static_configs:
      - targets: ["celery-exporter:9540"]

  - job_name: otel-collector
    static_configs:
      - targets: ["otel-collector:8889"]
